version: "2.1"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - /mnt/Dane4T/data4t/pyload:/downloads
    ports:
      - 8000:8000
#      - 9666:9666 #optional
    restart: unless-stopped
